apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: devops-system
roleRef:
  kind: ClusterRole
  name: filebeat
  #name: ibm-privileged-clusterrole
  apiGroup: rbac.authorization.k8s.io
