apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-sample-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus-sample-app
  template:
    metadata:
      labels:
        app: prometheus-sample-app
    spec:
      containers:
        - name: prometheus-sample-app
          image: open-o11y/prometheus-sample-app
          ports:
            - containerPort: 8080
