{{if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
spec:
  ingressClassName: nginx
  rules:
    - http:
       paths:
        - path: /
          pathType: Prefix

          backend:
            service:
              name: {{ .Release.Name }}-svc
              port:
                 number: {{ .Values.pod.port }}
{{end}}
