kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Release.Name }}-svc #from RELEASE NAME
spec:
  selector:
    app: {{ .Release.Name }}
{{if eq .Values.service_type "LoadBalancer"}}
  type: LoadBalancer    
{{else}}
  type: ClusterIP
{{end}}
  ports:         
  - name: http   
    protocol: TCP
    port: {{ .Values.pod.port }} #from Values
    targetPort: {{ .Values.pod.target_port }}  #from values

