apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
        canary: blue-green
    spec:
      containers:
      - name: green
        image: elevy99927/color:green
        ports:
        - containerPort: 80
